ci:
    autofix_commit_msg: 'refactor(lint): apply automatic lint fixes'
    autoupdate_commit_msg: 'chore(deps): bump pre-commit linter versions'

default_language_version:
    python: python3.11

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-shebang-scripts-are-executable
        exclude: '(root/etc/pulse/default.pa)|(root/~/.config/youtube-viewer/youtube-viewer.conf)'
    -   id: check-symlinks
    -   id: check-toml
    -   id: check-vcs-permalinks
    -   id: check-xml
        exclude: "%gconf.xml"
    -   id: check-yaml
        args: [--allow-multiple-documents]
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
        args: [--fix=lf]
    -   id: trailing-whitespace

# python
    -   id: check-ast
    -   id: check-builtin-literals
    -   id: check-docstring-first
    -   id: debug-statements
    -   id: double-quote-string-fixer
    -   id: name-tests-test
    -   id: requirements-txt-fixer
-   repo: https://github.com/PyCQA/pylint
    rev: v2.16.2
    hooks:
    -   id: pylint
        additional_dependencies:
        - pylint-import-modules==0.3.0
        args:
        - --allowed-direct-imports="typing.*"
        - --load-plugins=pylint_import_modules
        - --max-line-length=79
        - --max-args=10
        - --score=n
        - -d broad-except
        - -d duplicate-code
        - -d fixme
        - -d import-error
        - -d import-only-modules
        - -d invalid-name
        - -d locally-disabled
        - -d missing-docstring
        - -d too-few-public-methods
        - -d ungrouped-imports  # conflicts with reorder-python-imports
        - -d wrong-import-order  # conflicts with reorder-python-imports
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.4.2
    hooks:
    -   id: remove-crlf
    # -   id: remove-tabs  # TODO: enable
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
    -   id: reorder-python-imports
        args: [--py39-plus]
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
    -   id: pyupgrade
        args: [--py311-plus]
        exclude: 'root/etc/pythonstart'
-   repo: https://github.com/asottile/yesqa
    rev: v1.4.0
    hooks:
    -   id: yesqa
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.1
    hooks:
    -   id: autopep8
-   repo: https://github.com/PyCQA/pydocstyle
    rev: 6.3.0
    hooks:
    -   id: pydocstyle
        args:
        - --ignore=D1,D203,D205,D212,D400,D401,D404,D407,D412,D413
-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        additional_dependencies:
        - flake8-2020==1.7.0
          # - flake8-broken-line==0.6.0  # TODO: enable when they support flake6
        - flake8-builtins==2.0.1
        - flake8-commas==2.1.0
        - flake8-comprehensions==3.10.1
        - flake8-typing-imports==1.14.0
        args:
        - --ignore=E501,W503,F401,F811
-   repo: local
    hooks:
    -   id: pytest-fixture-require-scope
        name: Require explicit scope for pytest fixtures
        description: 'Ensure we explicitly set pytest fixture scopes'
        entry: '@pytest\.fixture( |\n|(\(\)))'
        language: pygrep
        types: [python]
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
    -   id: python-no-eval
    -   id: python-no-log-warn
    -   id: python-use-type-annotations

# rst
    -   id: rst-backticks
    -   id: rst-directive-colons
    -   id: rst-inline-touching-normal

# shell
# TODO: fix these checks
# -   repo: https://github.com/lovesegfault/beautysh
#     rev: v6.2.1
#     hooks:
#     -   id: beautysh
# -   repo: https://github.com/openstack/bashate
#     rev: 2.1.0
#     hooks:
#     -   id: bashate
#         args: [--max-line-length=80]
# -   repo: https://github.com/detailyang/pre-commit-shell
#     rev: 1.0.5
#     hooks:
#     -   id: shell-lint
# -   repo: https://github.com/jumanjihouse/pre-commit-hooks
#     rev: 2.1.6
#     hooks:
#     -   id: script-must-not-have-extension
