#!/usr/bin/env python3
import pathlib
from collections.abc import Iterator


HOME = pathlib.Path.home()
ROOT = pathlib.Path(__file__).parent / 'root' / '~'
FOLDERS = [
    '.config/nvim',
    '.config/pi/extensions',
    '.config/pi/prompts',
    '.config/pi/skills',
    '.config/tmuxifier/layouts',
    '.config/zsh/dropins',
    '.local/bin',
]
IGNORE = {
    'git-standup',  # TODO: sync with ./sync
    'lazy-lock.json',
}


def find(folder: str) -> Iterator[pathlib.Path]:
    for file in (HOME / folder).rglob('*'):
        if not file.is_file() or file.is_symlink() or file.name in IGNORE:
            continue

        sourcefile = ROOT / file.relative_to(HOME)
        m4file = sourcefile.with_suffix(f'{sourcefile.suffix}.m4')
        if not any(x.exists() for x in (sourcefile, m4file)):
            if not file.name.startswith('nobackup-'):
                yield file


def main() -> None:
    print('Discovering files in need of backup...')

    for folder in FOLDERS:
        files = list(find(folder))
        if files:
            print()
            print(f'The following files in {folder} may be in need of backup:')
            for file in files:
                print(file)


if __name__ == '__main__':
    main()
