#!/usr/bin/env bash
set -euo pipefail

if [[ "$@" == *"-h"* ]]; then
    echo "syncs your system from your dotsystem config"
    echo
    echo "Options:"
    echo "  --force             force over-write of all missing/modified files"
    echo "  --secrets           include LastPass secrets pull"
    echo "  --skip-packages     do not update installed packages"

    exit 0
fi

echo "Running dotsystem..."

if [[ ! -f ~/.ssh/id_ed25519 ]]; then
    echo "Detected fresh system, beginning bootstrap mode..."

    # set hostname
    read -p "Enter system hostname: " hostname
    sudo hostname "${hostname}"

    echo "Creating ~/.ssh/id_ed25519..."
    ssh-keygen -o -a 100 -t ed25519 -C "KevinJames@thekev.in" -f ~/.ssh/id_ed25519
    git remote set-url origin git@github.com:TheKevJames/dotsystem.git
fi

# Variables
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FORCE=$(if [[ "$@" == *"--force"* ]]; then echo "y"; else echo "n"; fi)

XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-~/.config}
XDG_DATA_HOME=${XDG_DATA_HOME:-~/.local/share}
XDG_SRC_HOME=${XDG_SRC_HOME:-~/.local/src}

if which zypper >/dev/null; then
    PACMAN_REFRESH="sudo zypper refresh"
    PACMAN_INSTALL="sudo zypper install"
elif which brew >/dev/null; then
    PACMAN_REFRESH="brew update"
    PACMAN_INSTALL="brew install"
elif which apt-get >/dev/null; then
    PACMAN_REFRESH="sudo apt-get update"
    PACMAN_INSTALL="sudo apt-get install"
else
    echo "ERROR: could not determine package manager."
    if [[ "$OSTYPE" == "darwin"* ]]; then
        echo "Install homebrew?"
        if [[ "${FORCE}" == "y" ]]; then
            ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
        else
            select yn in "Yes" "No"; do
                case $yn in
                    Yes ) ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)";
                          break;;
                    No )  break;;
                esac
            done
        fi
    fi
    exit 1
fi

# Helpers
ensure_dir() {
    if [ ! -d "$1" ]; then
        echo "Creating $1"
        mkdir -p "$1" 2>/dev/null || sudo mkdir -p "$1"
    fi
}

ensure_file() {
    ensure_dir $(dirname "$1")
    if [ ! -f "$1" ]; then
        touch "$1" 2>/dev/null || sudo touch "$1"
    fi
}

set_file() {
    DEST=${2/\~/$HOME}
    ensure_file "${DEST}"

    if ! sudo diff -q "${1}" "${DEST}" >/dev/null; then
        echo "${DEST} will be modified according to the following diff."
        sudo diff "${DEST}" "${1}" || true

        if [[ "${FORCE}" == "y" ]]; then
            cp "${1}" "${DEST}" 2>/dev/null || sudo cp "${1}" "${DEST}"
            if [[ "${DEST}" == *"/bin/"* ]]; then sudo chmod a+x "${DEST}"; fi
        else
            echo "Apply this change?"
            select yn in "Yes" "No"; do
                case $yn in
                    Yes ) cp "${1}" "${DEST}" 2>/dev/null || sudo cp "${1}" "${DEST}";
                          if [[ "${DEST}" == *"/bin/"* ]]; then sudo chmod a+x "${DEST}"; fi;
                          break;;
                    No )  break;;
                esac
            done
        fi
    fi
}

set_dir() {
    for file in "${1}/"*; do
        set_file "${file}" "${2}/$(basename ${file})"
    done
}

if [[ "$@" == *"--secrets"* ]]; then
    if [ ! -f "${XDG_CONFIG_HOME}/dotsystem/secrets" ]; then
        echo "Not loading secrets: none defined."
    elif ! which lpass >/dev/null; then
        echo "Not loading secrets: lpass not installed."
    else
        echo "Loading secrets..."
        for secret in $(cat "${XDG_CONFIG_HOME}/dotsystem/secrets"); do
            IFS=: read -a fields <<< "$secret"
            mkdir -p $(eval echo "${fields[1]%/*}")
            lpass show --note "${fields[0]}" > $(eval echo "${fields[1]}")
        done
    fi
fi

## Update global configs
echo "Configuring system..."

if [ ! -f "${XDG_DATA_HOME}/dotsystem/secrets.m4" ]; then
    echo "No secrets file found, writing defaults to ${XDG_DATA_HOME}/dotsystem/secrets.m4"
    cp ./secrets.m4.sample "${XDG_DATA_HOME}/dotsystem/secrets.m4"
fi

IFS=$(echo -en "\n\b"); for file in $(find "${DIR}/root" -type f); do
    if [[ "${file##*.}" == "m4" ]]; then
        TEMPFILE=$(mktemp)
        m4 ${XDG_DATA_HOME}/dotsystem/secrets.m4 $file 2>/dev/null > $TEMPFILE
        file_noext="${file%.*}"
        set_file "${TEMPFILE}" "/${file_noext#${DIR}/root/}"
    elif [[ "${file##*.}" == "once" ]]; then
        file_noext="${file%.*}"
        DEST="/${file_noext#${DIR}/root/}"
        DEST=${DEST/\~/$HOME}
        if [[ ! -f "$DEST" ]]; then
            set_file "${file}" "${DEST}"
        fi
    else
        set_file "${file}" "/${file#${DIR}/root/}"
    fi
done

## Configure OSX one-offs
if [[ "$OSTYPE" == "darwin"* ]]; then
    bash "${XDG_CONFIG_HOME}"/osx/config.sh

    # TODO: better multi-os paths
    IFS=$(echo -en "\n\b"); for file in $(find "${DIR}/root/~/.config/sublime-text-3" -type f); do
        set_file "${file}" "~/Library/Application Support/Sublime Text 3/${file#${DIR}/root/~/.config/sublime-text-3/}"
    done
fi

echo "done."

if [[ "$@" == *"--skip-packages"* ]]; then
    exit 0
fi

## Install packages
echo "Refreshing sources..."
eval "${PACMAN_REFRESH}" >/dev/null

packages=()
for package in $(cat "${XDG_CONFIG_HOME}/dotsystem/packages"); do
    IFS=: read -a fields <<< "$package"

    name="${fields[0]}"
    binary="${fields[1]:-${fields[0]}}"

    if ! which $name >/dev/null 2>&1 && ! which $binary >/dev/null 2>&1; then
        packages+=("${name}")
    fi
done

echo "Installing packages..."
if [[ "${packages[@]:-}" != "" ]]; then
    eval "${PACMAN_INSTALL} ${packages[@]}"
fi

## Configure OSX one-offs
if [[ "$OSTYPE" == "darwin"* ]]; then
    # force override of OSX's way out-of-date builtin
    if [[ ! -f "/usr/local/bin/zsh" ]]; then
        brew install zsh
        echo "/usr/local/bin/zsh" | sudo tee -a /etc/shells
    fi
fi

if grep -q "alacritty:sh" "${XDG_CONFIG_HOME}/dotsystem/packages"; then
    if [[ "$OSTYPE" == "darwin"* ]]; then
        if [[ ! -f /Applications/Alacritty.app/Contents/MacOS/alacritty ]]; then
            brew cask install alacritty
        fi
    else
        eval "${PACMAN_INSTALL} alacritty"
    fi
fi

if grep -q "franz:sh" "${XDG_CONFIG_HOME}/dotsystem/packages"; then
    if ! which franz >/dev/null; then
        TEMPFILE=$(mktemp)
        if [[ "$OSTYPE" == "darwin"* ]]; then
            brew cask install franz
            sudo ln -s /Applications/Franz.app/Contents/MacOS/Franz /usr/local/bin/franz

            mkdir -p ~/.config/Franz/recipes/dev/
            git clone git@github.com:TheKevJames/franz-recipe-dialpad.git ~/.config/Franz/recipes/dev/dialpad
        else
            curl -fsSL "https://github.com/meetfranz/franz-app/releases/download/4.0.4/Franz-linux-x64-4.0.4.tgz" > "${TEMPFILE}.tgz"
            tar xzf "${TEMPFILE}.tgz" -C /opt/franz
            sudo ln -s /opt/franz/Franz /usr/local/bin/franz

            mkdir -p ~/Library/Application\ Support/Franz/recipes/dev/
            git clone git@github.com:TheKevJames/franz-recipe-dialpad.git ~/Library/Application\ Support/Franz/recipes/dev/dialpad
        fi
    fi
fi

if grep -q "gcloud:sh" "${XDG_CONFIG_HOME}/dotsystem/packages"; then
    if ! which gcloud >/dev/null; then
        TEMPFILE=$(mktemp)
        if [[ "$OSTYPE" == "darwin"* ]]; then
            curl -fsSL "https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-258.0.0-darwin-x86_64.tar.gz" > "${TEMPFILE}.tgz"
        else
            curl -fsSL "https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-258.0.0-linux-x86_64.tar.gz" > "${TEMPFILE}.tgz"
        fi
        tar xzf "${TEMPFILE}.tgz" -C "${XDG_SRC_HOME}"
    fi
fi

if grep -q "gpg:gnupg" "${XDG_CONFIG_HOME}/dotsystem/packages"; then
    if [[ "$OSTYPE" == "darwin"* ]]; then
        if ! which pinentry-mac >/dev/null; then
            brew install pinentry-mac
        fi
    fi
fi

if grep -q "hexyl:sh" "${XDG_CONFIG_HOME}/dotsystem/packages"; then
    if ! which hexyl >/dev/null; then
        if [[ "$OSTYPE" == "darwin"* ]]; then
            brew install hexyl
        else
            TEMPFILE=$(mktemp)
            curl -fsSL "https://github.com/sharkdp/hexyl/releases/download/v0.4.0/hexyl-v0.4.0-x86_64-unknown-linux-gnu.tar.gz" > "${TEMPFILE}.tgz"
            tar xzf "${TEMPFILE}.tgz" -C "${TMPDIR:-/tmp}"
            sudo mv "${TMPDIR:-/tmp}"/hexyl-*/hexyl /usr/local/bin
        fi
    fi
fi

if grep -q "hub:sh" "${XDG_CONFIG_HOME}/dotsystem/packages"; then
    if ! which hub >/dev/null; then
        if [[ "$OSTYPE" == "darwin"* ]]; then
            brew install hub
        else
            TEMPFILE=$(mktemp)
            curl -fsSL "https://github.com/github/hub/releases/download/v2.5.0/hub-linux-amd64-2.5.0.tgz" > "${TEMPFILE}.tgz"
            tar xzf "${TEMPFILE}.tgz" -C "${TMPDIR:-/tmp}"
            sudo mv "${TMPDIR:-/tmp}"/hub-*/bin/hub /usr/local/bin
        fi
    fi
fi

if grep -q "jira:sh" "${XDG_CONFIG_HOME}/dotsystem/packages"; then
    if ! which jira >/dev/null; then
        if [[ "$OSTYPE" == "darwin"* ]]; then
            sudo curl -fsSLo /usr/local/bin/jira "https://github.com/Netflix-Skunkworks/go-jira/releases/download/v1.0.20/jira-darwin-10.6-amd64"
        else
            sudo curl -fsSLo /usr/local/bin/jira "https://github.com/Netflix-Skunkworks/go-jira/releases/download/v1.0.20/jira-linux-amd64"
        fi
        sudo chmod a+x /usr/local/bin/jira
    fi
fi

if grep -q "neovim:nvim" "${XDG_CONFIG_HOME}/dotsystem/packages"; then
    if [ ! -f "${XDG_DATA_HOME}/nvim/site/autoload/plug.vim" ]; then
        curl -fsSLo "${XDG_DATA_HOME}/nvim/site/autoload/plug.vim" --create-dirs "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    fi
fi

if grep -q "ngrok:sh" "${XDG_CONFIG_HOME}/dotsystem/packages"; then
    if ! which ngrok >/dev/null; then
        TEMPFILE=$(mktemp)
        if [[ "$OSTYPE" == "darwin"* ]]; then
            curl -fsSL "https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-darwin-amd64.zip" > "${TEMPFILE}.zip"
        else
            curl -fsSL "https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip" > "${TEMPFILE}.zip"
        fi
        sudo unzip "${TEMPFILE}.zip" -d /usr/local/bin
    fi
fi

if grep -q "prettyping:sh" "${XDG_CONFIG_HOME}/dotsystem/packages"; then
    if ! which prettyping >/dev/null; then
        sudo curl -fsSLo /usr/local/bin/prettyping "https://raw.githubusercontent.com/denilsonsa/prettyping/master/prettyping"
        sudo chmod a+x /usr/local/bin/prettyping
    fi
fi

if grep -q "sublime-text:sh" "${XDG_CONFIG_HOME}/dotsystem/packages"; then
    if ! which subl >/dev/null; then
        TEMPFILE=$(mktemp)
        if [[ "$OSTYPE" == "darwin"* ]]; then
            brew cask install sublime-text
            sudo ln -s "/Applications/Sublime Text.app/Contents/MacOS/Sublime Text" /usr/local/bin/subl
        else
            eval "${PACMAN_INSTALL} sublime-text"
        fi
    fi
fi

if grep -q "taskwarrior:sh" "${XDG_CONFIG_HOME}/dotsystem/packages"; then
    if ! which task >/dev/null; then
        if [[ "$OSTYPE" == "darwin"* ]]; then
            eval "${PACMAN_INSTALL} task"
        else
            eval "${PACMAN_INSTALL} taskwarrior"
        fi
    fi
fi

if grep -q "tmuxifier:sh" "${XDG_CONFIG_HOME}/dotsystem/packages"; then
    if ! which tmuxifier >/dev/null; then
        git clone https://github.com/jimeh/tmuxifier.git "${XDG_SRC_HOME}/tmuxifier"
    fi
fi

if grep -q "transmission-daemon:sh" "${XDG_CONFIG_HOME}/dotsystem/packages"; then
    if ! which transmission-daemon >/dev/null; then
        if [[ "$OSTYPE" == "darwin"* ]]; then
            eval "${PACMAN_INSTALL} transmission"
        else
            eval "${PACMAN_INSTALL} transmission-daemon"
        fi
    fi
fi
