endpoint: https://switchcomm.atlassian.net
login: kjames@dialpad.com
user: kjames
password-source: keyring

custom-commands:
  - name: kanban
    help: Display team kanban board
    options:
      - name: sort
        short: s
        default: assignee,status
    script: |-
      {{jira}} ls -tkanban --query="assignee IN (allan.hamzic, eddie, e.galpin, hsaini, jonathan, jpalmer, kjames, k.hersey, ssawyer) AND status NOT IN ('Backlog', 'Closed', 'Done') ORDER BY {{options.sort}}"
  - name: mine
    help: Display issues assigned to me
    script: |-
      {{jira}} ls -tkanban -akjames -sstatus
  - name: next
    help: Display upcoming tasks for the team
    script: |-
      {{jira}} ls -tbacklog --query="assignee IS NULL AND project=VAE AND status IN ('To Do', 'Needs Triage') ORDER BY priority"
  - name: ready
    help: Transition issue to "Ready for Production" state
    args:
      - name: ISSUE
        required: true
    script: |-
      {{jira}} transition --noedit 'Ready' {{args.ISSUE}}
  - name: review
    help: Transition issue to "Code Review" state
    args:
      - name: ISSUE
        required: true
    script: |-
      {{jira}} transition --noedit 'Review' {{args.ISSUE}}
  - name: triage
    help: Transition issue to "In Triage" state
    args:
      - name: ISSUE
        required: true
    script: |-
      {{jira}} transition --noedit 'Triage' {{args.ISSUE}}
