version: 2.1

orbs:
  pre-commit: https://raw.githubusercontent.com/TheKevJames/tools/refs/heads/master/circleci-orbs/pre-commit.yml

executors:
  python:
    docker:
      - image: python:3.14.7
    resource_class: medium

workflows:
  run-jobs:
    jobs:
      - pre-commit/pre-commit:
          executor: python
