repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-toml
    -   id: check-vcs-permalinks
    -   id: check-xml
    -   id: check-yaml
        args: [--allow-multiple-documents]
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
        args: [--fix=lf]
    -   id: trailing-whitespace

# python
    -   id: check-ast
    -   id: check-builtin-literals
    -   id: check-docstring-first
    -   id: debug-statements
    -   id: double-quote-string-fixer
    -   id: name-tests-test
    -   id: requirements-txt-fixer
-   repo: https://github.com/pycqa/pylint
    rev: pylint-2.6.0
    hooks:
    -   id: pylint
        additional_dependencies:
        # TODO: >0.2.0
        - git+https://github.com/bayesimpact/pylint_import_modules@016f79e4d2
        args:
        - --allowed-direct-imports="typing.*"
        - --load-plugins=pylint_import_modules
        - --max-line-length=79
        - --max-args=10
        - --score=n
        - -d broad-except
        - -d duplicate-code
        - -d fixme
        - -d import-error
        - -d import-only-modules
        - -d invalid-name
        - -d locally-disabled
        - -d missing-docstring
        - -d too-few-public-methods
        - -d ungrouped-imports  # conflicts with reorder-python-imports
        - -d wrong-import-order  # conflicts with reorder-python-imports
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.9
    hooks:
    -   id: remove-crlf
    -   id: remove-tabs
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.3.5
    hooks:
    -   id: reorder-python-imports
        args: [--py37-plus]
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.7.3
    hooks:
    -   id: pyupgrade
        args: [--py37-plus]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.790
    hooks:
    -   id: mypy
        require_serial: True
        args:
        - --ignore-missing-imports
        - --follow-imports=silent
        - --show-error-codes
        - --strict
        - --strict-equality
        - --warn-unreachable
        exclude: tests/.*
-   repo: https://github.com/asottile/yesqa
    rev: v1.2.2
    hooks:
    -   id: yesqa
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.5
    hooks:
    -   id: autopep8
-   repo: https://github.com/PyCQA/pydocstyle
    rev: 5.1.1
    hooks:
    -   id: pydocstyle
        args:
        - --ignore=D1,D203,D205,D212,D400,D401,D404,D413
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    -   id: flake8
        args:
        - --ignore=E501,W503,F401,F811
-   repo: local
    hooks:
    -   id: pytest-fixture-require-scope
        name: Require explicit scope for pytest fixtures
        description: 'Ensure we explicitly set pytest fixture scopes'
        entry: '@pytest\.fixture( |\n|(\(\)))'
        language: pygrep
        types: [python]
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.6.0
    hooks:
    -   id: python-no-eval
    -   id: python-no-log-warn
    -   id: python-use-type-annotations

# rst
    -   id: rst-backticks
    -   id: rst-inline-touching-normal

# java
-   repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v1.5.0
    hooks:
    -   id: pretty-format-java
        args: [--autofix]

# javascript
-   repo: https://github.com/pre-commit/mirrors-fixmyjs
    rev: v2.0.0
    hooks:
    -   id: fixmyjs
-   repo: https://github.com/pre-commit/mirrors-jshint
    rev: v2.12.0
    hooks:
    -   id: jshint

# terraform
-   repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.43.0
    hooks:
    -   id: terraform_fmt
    -   id: terraform_validate

# shell
-   repo: https://github.com/lovesegfault/beautysh
    rev: 6.0.1
    hooks:
    -   id: beautysh
-   repo: https://github.com/openstack/bashate
    rev: 2.0.0
    hooks:
    -   id: bashate
        args: [--max-line-length=80]
-   repo: https://github.com/detailyang/pre-commit-shell
    rev: 1.0.5
    hooks:
    -   id: shell-lint
-   repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.4
    hooks:
    -   id: script-must-not-have-extension
