#!/usr/bin/env python
import atexit
import os
import readline
import rlcompleter
import sys


HISTORY = os.path.expanduser(os.path.join(
    os.environ.get('XDG_DATA_HOME', '~/.local/share'),
    'python{}'.format(sys.version_info[0]), 'history'))
if not os.path.exists(HISTORY):
    open(HISTORY, 'a').close()

# Load
readline.set_history_length(10000)
readline.read_history_file(HISTORY)

readline.parse_and_bind('tab: complete')

# Save
def save_history(history_path=HISTORY):
    import readline
    readline.write_history_file(history_path)

atexit.register(save_history)

# Remove from namespace
del atexit, os, readline, rlcompleter, sys
del HISTORY
del save_history
